[project]
name = "gridcast-uk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "leohsin", email = "leohsin2002@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
gridcast-uk = "gridcast_uk:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
